src/IBVL.Sistema.Web/Entities/Teste.cs
namespace IBVL.Sistema.Web.Entities
{
    public class Teste
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

src/IBVL.Sistema.Web/Models/ErrorViewModel.cs
namespace IBVL.Sistema.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/IBVL.Sistema.Web/Controllers/HomeController.cs
using IBVL.Sistema.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IBVL.Sistema.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/IBVL.Sistema.Web/Controllers/MembroController.cs
using IBVL.Sistema.Application.Dtos;
using Microsoft.AspNetCore.Mvc;
using WSCorreiros;

namespace IBVL.Sistema.Web.Controllers
{
    public class MembroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        public IActionResult Create(MembroDto membroDto)
            {
            if (!ModelState.IsValid) return BadRequest(membroDto);

            return View();
        }


        [HttpGet, ActionName("BuscaCep")]
        public async Task<IActionResult> Create(string cep)
        {
            var endereco = await BuscaCepAsync(cep);

            return View(endereco);
        }


        private async Task<EnderecoDto> BuscaCepAsync(string cep)
        {
            var ws = new AtendeClienteClient();
            consultaCEPResponse end = await ws.consultaCEPAsync(cep);

            EnderecoDto endereco = new()
            {
                CEP = cep,
                Logradouro = end.@return.end,
                Cidade = end.@return.cidade,
                Bairro = end.@return.bairro,
                Estado = end.@return.uf,
                Complemento = end.@return.complemento2

            };

            return endereco;

        }











    }

}

src/IBVL.Sistema.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/IBVL.Sistema.Web/Views/Membro/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/IBVL.Sistema.Web/Views/Membro/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/IBVL.Sistema.Web/Views/Membro/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/IBVL.Sistema.Web/Views/Membro/EnderecoParcial.cshtml
@model IBVL.Sistema.Application.Dtos.MembroDto

<form class="row g-3 needs-validation" novalidate asp-action="Create" method="post">
    <input type="hidden" asp-for="Endereco.CEP" />
    <div class="col-md-3">
        <label for="validationCustom01" class="form-label">CEP</label>
        <input type="text" class="form-control" id="validationCustom01" asp-for="Endereco.CEP" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-md-7">
        <label for="validationCustom01" class="form-label">Logradouro</label>
        <input type="text" class="form-control" id="validationCustom01" asp-for="Endereco.Logradouro" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom02" class="form-label">Numero</label>
        <input type="text" class="form-control" id="validationCustom02" asp-for="Endereco.Numero" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>   
    <div class="col-md-3">
        <label for="validationCustom04" class="form-label">Cidade</label>
        <select asp-for="Endereco.Cidade" class="form-select" id="validationCustom04" required>
            <option value="">Duque de Caxias</option>           
            <option selected disable>...</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-3">
        <label for="validationCustom04" class="form-label">Bairro</label>
        <select asp-for="Endereco.Bairro" class="form-select" id="validationCustom04" required>
            <option value="">Vila Leopoldina</option>
            <option selected disable>...</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-1">
        <label for="validationCustom04" class="form-label">Estado</label>
        <select asp-for="Endereco.Cidade" class="form-select" id="validationCustom04" required>
            <option value="">RJ</option>
            <option selected disable>...</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-5">
        <label for="validationCustom02" class="form-label">Complemento</label>
        <input type="text" class="form-control" id="validationCustom02" asp-for="Endereco.Numero" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
      
    <div class="col-12">
        <button class="btn btn-primary" type="submit">Submit form</button>
    </div>
</form>

src/IBVL.Sistema.Web/Views/Membro/Index.cshtml
@model IBVL.Sistema.Application.Dtos.MembroDto

<form class="row g-3 needs-validation" novalidate asp-action="Create" method="post">
    <div class="col-md-4">


        <label for="validationCustom01" class="form-label">Nome Completo</label>
        <input type="text" class="form-control" id="validationCustom01" asp-for="Nome" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom02" class="form-label">Apelido</label>
        <input type="text" class="form-control" id="validationCustom02" asp-for="Apelido" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom02" class="form-label">Data Nascimento</label>
        <input type="date" class="form-control" id="validationCustom02" asp-for="DataNascimento" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom04" class="form-label">Sexo</label>
        <select asp-for="Sexo" class="form-select" id="validationCustom04" required>
            <option value="Feminino">Feminino</option>
            <option value="Masculino">Masculino</option>
            <option selected disable>...</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom04" class="form-label">Etnia</label>
        <select asp-for=Etnia class="form-select" id="validationCustom04" required>
            <option value="Amarela">Amarela</option>
            <option value="Branca">Branca</option>
            <option value="Indígena">Indígena</option>
            <option value="Parda">Parda</option>
            <option value="Preta">Preta</option>
            <option value="Outra">Outra</option>
            <option selected disable>...</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-4">
        <label for="validationCustomUsername" class="form-label" asp-for="Email">Email</label>
        <div class="input-group has-validation">
            <span class="input-group-text" id="inputGroupPrepend">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-at" viewBox="0 0 16 16">
                    <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2H2Zm3.708 6.208L1 11.105V5.383l4.708 2.825ZM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2-7-4.2Z" />
                    <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648Zm-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z" />
                </svg>
            </span>
            <input type="datetime" class="form-control" id="validationCustomUsername" asp-for="DataNascimento" aria-describedby="inputGroupPrepend" required>
            <div class="invalid-feedback">
                Please choose a username.
            </div>
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom04" class="form-label">Estado Civíl</label>
        <select asp-for="EstadoCivil" class="form-select" id="validationCustom04" required>
            <option value="Casado(a)">Casado(a) </option>
            <option value="Divorciado(a)">Divorciado(a)</option>
            <option value="Separado(a)">Separado(a)</option>
            <option value="Solteiro(a)">Solteiro(a)</option>
            <option value="Viuvo(a)">Viúvo(a)</option>
            <option selected disable>...</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom04" class="form-label">Naturalidade</label>
        <select asp-for="Naturalidade" class="form-select" id="validationCustom04" required>
            <option value=""></option>
            <option selected disable value="Brasileiro(a)">RJ</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom04" class="form-label">Nacionalidade</label>
        <select asp-for="Nacionalidade" class="form-select" id="validationCustom04" required>
            <option value=""></option>
            <option selected disable value="Brasileiro(a)">Brasileiro(a)</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>

    <div class="col-md-2">
        <label for="validationCustom04" class="form-label">Grupo Sanquineo</label>
        <select asp-for="GrupoSanquineo" class="form-select" id="validationCustom04" required>
            <option value=""></option>
            <option value="O_Positivo">O+</option>
            <option value="O_Negativo(a)">O-</option>
            <option value="A_Positivo(a)">A+</option>
            <option value="A_Negativo(a)">A-</option>
            <option value="B_Positivo(a)">B+</option>
            <option value="B_Negativo(a)">B-</option>
            <option value="AB_Positivo(a)">AB+</option>
            <option value="ViuvoAB_Negativoa)">AB-</option>
            <option selected disable value="Brasileiro(a)">...</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom05" class="form-label">RG</label>
        <input type="text" class="form-control" asp-for="RG" id="validationCustom05" required>
        <div class="invalid-feedback">
            Please provide a valid zip.
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom05" class="form-label">CPF</label>
        <input type="text" class="form-control" asp-for="CPF" id="validationCustom05" required>
        <div class="invalid-feedback">
            Please provide a valid zip.
        </div>
    </div>
    <div class="col-md-2">
        <label for="validationCustom04" class="form-label">Situação</label>
        <select asp-for="Situacao" class="form-select" id="validationCustom04" required>
            <option value="AfastadoVoluntariamente(a)">Atastado Voluntariamente</option>
            <option value="DesligadoVoluntariamente(a)">Desligado Voluntariamente</option>
            <option value="Excluido(a)">Excluido</option>
            <option value="Impossibilitado(a)">Impossibilitado</option>
            <option value="Transferido(a)">Transferido</option>
            <option value="Falecido(a)">Falecido</option>
            <option selected disable value="Ativo">Ativo</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid state.
        </div>
    </div>
    <div class="col-md-3">
        <label for="validationCustom02" class="form-label">Data Admissão</label>
        <input type="datetime-local" class="form-control" id="validationCustom02" asp-for="DataAdimissao" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-md-3">
        <label for="validationCustom02" class="form-label">Data desligamento</label>
        <input type="datetime-local" class="form-control" id="validationCustom02" asp-for="DataDesligamento" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" asp-for="EhBatizado" id="flexSwitchCheckChecked" checked>
            <label for="validationCustom06" class="form-label">Eh Batizado</label>
        </div>
        <div class="invalid-feedback">
            You must agree before submitting.
        </div>
    </div>

    <div class="col-md-12 " style="margin-top:0">
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" asp-for="EhDizimista" id="flexSwitchCheckChecked" checked>
            <label for="validationCustom06" class="form-label">Eh Dizimista</label>
        </div>
        <div class="invalid-feedback">
            You must agree before submitting.
        </div>
    </div>

    <div class="col-md-12">
        <div class="form-floating">
            <textarea class="form-control" asp-for="Observacao" id="floatingTextarea2" style="height: 100px"></textarea>
            <label for="floatingTextarea2">Observação</label>
            <div class="invalid-feedback">
                You must agree before submitting.
            </div>
        </div>
    </div>

    <h2>Endereco: </h2>
    <hr />
    <partial name="EnderecoParcial" />

    <div class="col-12">
        <button class="btn btn-primary" type="submit">Pesquisar CEP</button>
    </div>
</form>


@*<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>*@

src/IBVL.Sistema.Web/Views/Membro/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/IBVL.Sistema.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IBVL.Sistema.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IBVL.Sistema.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IBVL.Sistema.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Membro" asp-action="Index">Membro

                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IBVL.Sistema.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>